"""empty message

Revision ID: 1b1edff34780
Revises: 63d9c92afff7
Create Date: 2024-06-13 17:32:09.095563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b1edff34780'
down_revision = '63d9c92afff7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.alter_column('design_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hashed', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_hashed')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.alter_column('design_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
